from models.RFTraining import *
from models.XGBTraining import *
from models.LGBTraining import *
from models.CatTraining import *
from models.LRTraining import *
from models.RidgeTraining import *
from models.SVRTraining import *
from models.MLPTraining import *
from models.GSRTraining import *